<div class="layout left">
	<p>Débutant, je m'intéresse à la création de site Web depuis début 2016. J'ai d'abord commencé à me former seul, ce qui m'a permis de concrétiser mon intérêt pour la chose. J'ai ensuite suivi une formation pour intensifier mes connaissances.</p>
	<p>J'aime le Back-End pour la rigueur que ça impose. J'aime faire les choses au mieux, le plus sécurisé et le plus optimisé possible.</p>
	<p>J'aime le Front-End pour la liberté que ça offre. J'aime pouvoir laisser libre court à mon imagination pour offrir un visuel intuitif et responsive.</p>
</div>
<div class="layout right">
</div>