<div class="layout left">
	<section class="sheet">
		<h2>Fiche Technique</h2>
		<ul>
			<li>
				<p>Prénom: Kévin</p>
			</li>
			<li>
				<p>Nom: Pique</p>
			</li>
			<li>
				<p>Pseudo: DoudouPike</p>
			</li>
			<li>
				<p>Profession: Développeur Web Front & Back End</p>
			</li>
			<li>
				<p>Passions: Sciences, Jeux vidéos, Fight Club</p>
			</li>
		</ul>
	</section>
	<section class="about">
		<p>Débutant, je m'intéresse à la création de site Web depuis début 2016. J'ai d'abord commencé à me former seul, ce qui m'a permis de concrétiser mon intérêt pour la chose. J'ai ensuite suivi une formation pour intensifier mes connaissances.</p>
		<p>J'aime le Back-End pour la rigueur que ça impose. J'aime faire les choses au mieux, le plus sécurisé et le plus optimisé possible.</p>
		<p>J'aime le Front-End pour la liberté que ça offre. J'aime pouvoir laisser libre cours à mon imagination pour offrir un visuel intuitif et responsive.</p>
	</section>
</div>
<div class="layout right">
	<section class="skill">
		<h2>Compétences</h2>
		<div id="skillBox" class="skillBox">
			<svg class="graph" viewBox="0 0 84100 59400">
				<!-- outline -->
				<circle class="graphElement" id="outline" cx="41710" cy="25182" r="22526" fill='none' stroke="rgb(26,26,26)" stroke-width="100"/>
				<!-- html -->
				<path class="graphElement html" d="M 41710,2690 C 39350,2690 37004,3061 34759,3790 32515,4520 30399,5598 28489,6985 26580,8373 24901,10052 23513,11961 22126,13871 21048,15987 20318,18231 19589,20476 19218,22822 19218,25182 L 41710,25182 41710,25182 41710,25182 41710,25182 41710,25182 41710,25182 41710,2690 Z"/>
				<!-- css -->
		        <path class="graphElement css" d="M 19218,25182 C 19218,27542 19589,29888 20318,32134 21048,34378 22126,36494 23513,38404 24901,40313 26580,41992 28489,43380 30399,44767 32515,45845 34759,46575 37004,47304 39350,47676 41710,47676 L 41710,25182 41710,25182 41710,25182 41710,25182 41710,25182 41710,25182 19218,25182 Z"/>
		        <!-- php -->
		        <path class="graphElement php" d="M 41710,47676 C 44070,47676 46416,47304 48661,46575 50905,45845 53021,44767 54931,43380 56840,41992 58519,40313 59907,38404 61294,36494 62372,34378 63102,32134 63831,29888 64203,27542 64203,25182 L 41710,25182 41710,25182 41710,25182 41710,25182 41710,25182 41710,25182 41710,47676 Z"/>
		        <!-- mysql -->
		        <path class="graphElement mysql" d="M 64203,25182 C 64203,22822 63831,20476 63102,18231 62372,15987 61294,13871 59907,11961 58519,10052 56840,8373 54931,6985 53021,5598 50905,4520 48661,3790 L 41710,25182 41710,25182 41710,25182 41710,25182 41710,25182 64203,25182 Z"/>
		        <!-- js -->
		        <path class="graphElement js" d="M 48661,3790 C 46416,3061 44070,2690 41710,2690 L 41710,25182 41710,25182 48661,3790 Z"/>
		        <!-- Code html -->
		        <path class="graphElement html" fill="rgb(20,20,20)" stroke="black" stroke-width="30" d="M 4236,54074 L 3220,54074 3220,52042 5252,52042 5252,54074 4236,54074 Z"/>
		        <!-- Code css -->
		        <path class="graphElement css" fill="rgb(70,70,70)" stroke="black" stroke-width="30" d="M 19202,54074 L 18186,54074 18186,52042 20218,52042 20218,54074 19202,54074 Z"/>
		        <!-- Code php -->
		        <path class="graphElement php" fill="rgb(120,120,120)" stroke="black" stroke-width="30" d="M 31892,54074 L 30876,54074 30876,52042 32908,52042 32908,54074 31892,54074 Z"/>
		        <!-- Code mysql -->
		        <path class="graphElement mysql" fill="rgb(170,170,170)" stroke="black" stroke-width="30" d="M 44582,54074 L 43566,54074 43566,52042 45598,52042 45598,54074 44582,54074 Z"/>
		        <!-- Code js -->
		        <path class="graphElement js" fill="rgb(230,230,230)" stroke="black" stroke-width="30" d="M 61558,54074 L 60542,54074 60542,52042 62574,52042 62574,54074 61558,54074 Z"/>
		        <!-- Legend html -->
		        <text class="graphElement html"><tspan x="5997" y="54209">HTML</tspan></text>
		        <!-- Legend css -->
		        <text class="graphElement css"><tspan x="20963" y="54209">CSS</tspan></text>
		        <!-- Legend php -->
		        <text class="graphElement php"><tspan x="33653" y="54209">PHP</tspan></text>
		        <!-- Legend mysql -->
		        <text class="graphElement mysql"><tspan x="46343" y="54209">MySQL</tspan></text>
		        <!-- Legend js -->
		        <text class="graphElement js"><tspan font-size="3387px"><tspan x="63319" y="54209">JS / jQuery</tspan></tspan></text>
		    </svg>
		    <div class="specific">
		    	<p class="graphElement html">Lorem ipsum dolor sit amet, consectetur aoluptate. Animi a impedit vel eaque adipisci rem est dicta ullam.</p>
		    	<p class="graphElement css">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur soluta libero repellendus dignissimos quo aspernatur rem suscipit laboriosam obcae</p>
		    	<p class="graphElement php">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum iure enim deserunt hic esse impedit reprehenderit, suscipit vel quaerat. Bea!</p>
		    	<p class="graphElement mysql">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus at aperiam assumenda, veritatis ipsam. Quibusdam labore, fuga assumenda dignissimos </p>
		    	<p class="graphElement js">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam debitis porro quidem explicabo quaerat quae sint. Harum quia, asperiores archit.</p>
		    </div>
		</div>
	</section>
	<section class="career">
		<p>CACA</p>
	</section>
</div>