<div class="layout left">
	<h2>À propos de moi</h2>
	<div class="sheet">
		<ul>
			<li>
				<p class="user_info"><span>Prénom :</span>Kévin</p>
			</li>
			<li>
				<p class="user_info"><span>Nom :</span> Pique</p>
			</li>
			<li>
				<p class="user_info"><span>Pseudo :</span> DoudouPike</p>
			</li>
			<li>
				<p class="user_info"><span>Profession :</span>Développeur Web Front & Back End</p>
			</li>
			<li>
				<p class="user_info"><span>Localisation :</span>Alsace</p>
			</li>
			<li>
				<p class="user_info"><span>Centres d'intérêt :</span>Philosophie / Psychologie Sociale, Jeux vidéos, Fight Club</p>
			</li>
		</ul>
	</div>
	<div class="about">
		<p>Débutant, je m'intéresse à la création de site Web depuis début 2016. J'ai d'abord commencé à me former seul, ce qui m'a permis de concrétiser mon intérêt pour la chose. J'ai ensuite suivi une <a href="http://3wa.fr" title="3W Academy" target="_blank">formation</a> pour intensifier mes connaissances. Depuis, je continue de me former en autodidacte.</p>
		<p>Je suis à l'aise en Front comme en Back End. J'aime réaliser un projet de A à Z, mais je me sens également à l'aise au sein d'une équipe. Bref, je suis polyvalent.</p>
		<p class="freelance">Depuis le 15 avril 2017, je suis Micro-Entrepreneur. Je peux donc réaliser vos projets webs !
		<br>Que votre projet soit déjà clair ou non, je tiens à vous accompagner dans la définition de vos besoins. Je compte avant tout vous proposer des services qui vous conviennent vraiment !
		<br>Je peux donc intervenir de la définition de vos besoins, en passant par la création du site et d'images simples, jusqu'à la maintenance et l'entretien de votre site. <a href="index.php?page=contact">Contactez-moi !</a></p>
	</div>
	<div class="cv">
		<p><a href="public/documents/cv.pdf">Voir / Télécharcher mon CV</a></p>
	</div>

	<a class="toggle_large scrollArrow" href="index.php?page=about&s"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>

</div>
<div class="layout right">

	<div class="toggle_large scrollTarget"></div>

	<section class="skill">
		<h2>Compétences</h2>
		<p><em>(en noir les technologies que je suis en train d'acquérir)</em></p>
		<ul class="skills">
			<li class="singleSkill">
				<div class="pourcentBar"><p class="pourcentValue html"><strong>HTML</strong> <span>80%</span></p></div>
				<div class="specific"><p>HTML5</p></div>
			</li>
			<li class="singleSkill">
				<div class="pourcentBar"><p class="pourcentValue css"><strong>CSS</strong> <span>80%</span></p></div>
				<div class="specific"><p>CSS3, Responsive Design, LESS, Bootstrap</p></div>
			</li>
			<li class="singleSkill">
				<div class="pourcentBar"><p class="pourcentValue php"><strong>PHP</strong> <span>70%</span></p></div>
				<div class="specific"><p>PHP5, POO, <i class="fa fa-lock" aria-hidden="true"></i> XSS/SQLi</p></div>
			</li>
			<li class="singleSkill">
				<div class="pourcentBar"><p class="pourcentValue mysql"><strong>MySQL</strong><span>70%</span></p></div>
				<div class="specific"><p>Jointures</p></div>
			</li>
			<li class="singleSkill">
				<div class="pourcentBar"><p class="pourcentValue js"><strong>JavaScript</strong><span>50%</span></p></div>
				<div class="specific"><p>jQuery, <em>AJAX</em></p></div>
			</li>
			<li class="otherSkill">
				<div class="CMS"><p><strong>CMS</strong><span>WordPress(<em>Création de thèmes/plugins</em>)</span></p></div>
				<div class="other"><p><strong>Autres</strong><span>Git, PhpMyAdmin, MVC, Prepros, <em>Inkscape</em></span></p></div>
			</li>
		</ul>
	
	</section>
	<section class="career">
		<h2>Parcours</h2>
		<div id="schema" class="schema">
			<svg viewBox="0 0 84100 59400">
				<title>Mon parcours</title>
				
				<g class="schemaElement old">
		    		<path d="M 42050,59400 L 0,59400 0,49300 84100,49300 84100,59400 42050,59400 Z"/>
					<text x="16917" y="55523">Ancienne carrière professionnelle</text>
				</g>
				
				<g class="schemaElement formation">
					<path d="M 57650,42700 L 34300,42700 34300,32600 81000,32600 81000,42700 57650,42700 Z"/>
					<text x="38264" y="38823">Formation Dev Web</text>
				</g>
				
				<g class="schemaElement perso">
					<path d="M 26450,26800 L 3100,26800 3100,16700 49800,16700 49800,26800 26450,26800 Z"/>
					<text x="11642" y="22923">Réalisations perso</text>
				</g>

				<g class="schemaElement work">
					<path d="M 42050,10200 L 0,10200 0,100 84100,100 84100,10200 42050,10200 Z"/>
					<text x="17389" y="6323">Nouvelle carrière professionnelle</text>
				</g>
				
				<path id="old1" class="schemaElement arrow" d="M 40300,48900 L 40781,48556"/>
				<path id="old2" class="schemaElement arrow" d="M 41262,48213 L 41743,47869"/>
				<path id="old3" class="schemaElement arrow" d="M 42224,47526 L 42705,47182"/>
				<path id="old4" class="schemaElement arrow" d="M 43185,46839 L 43666,46495"/>
				<path id="old5" class="schemaElement arrow" d="M 44147,46152 L 44628,45808"/>
				<path id="old6" class="schemaElement arrow" d="M 45109,45465 L 45590,45121"/>
				<path id="old7" class="schemaElement arrow" d="M 46071,44778 L 46552,44434"/>
				<path id="old8" class="schemaElement arrow" d="M 47033,44091 L 47300,43900"/>
				<path id="old9" class="schemaElement arrow" d="M 48700,42900 L 46887,43458 47584,44434 48700,42900 Z"/>

				<path id="form1" class="schemaElement arrow" d="M 50500,32200 L 49965,31949"/>
				<path id="form2" class="schemaElement arrow" d="M 49430,31699 L 48894,31448"/>
				<path id="form3" class="schemaElement arrow" d="M 48359,31197 L 47824,30946"/>
				<path id="form4" class="schemaElement arrow" d="M 47289,30696 L 46754,30445"/>
				<path id="form5" class="schemaElement arrow" d="M 46219,30194 L 45683,29944"/>
				<path id="form6" class="schemaElement arrow" d="M 45148,29693 L 44613,29442"/>
				<path id="form7" class="schemaElement arrow" d="M 44078,29191 L 43543,28941"/>
				<path id="form8" class="schemaElement arrow" d="M 43007,28690 L 42472,28439"/>
				<path id="form9" class="schemaElement arrow" d="M 41937,28189 L 41402,27938"/>
				<path id="form10" class="schemaElement arrow" d="M 39400,27000 L 40775,28307 41285,27220 39400,27000 Z"/>
				
				<path id="perso1" class="schemaElement arrow" d="M 33217,16456 L 33708,16127"/>
				<path id="perso2" class="schemaElement arrow" d="M 34200,15800 L 34692,15472"/>
				<path id="perso3" class="schemaElement arrow" d="M 35183,15144 L 35675,14817"/>
				<path id="perso4" class="schemaElement arrow" d="M 36167,14489 L 36659,14161"/>
				<path id="perso5" class="schemaElement arrow" d="M 37150,13833 L 37642,13505"/>
				<path id="perso6" class="schemaElement arrow" d="M 38134,13177 L 38626,12850"/>
				<path id="perso7" class="schemaElement arrow" d="M 39117,12522 L 39609,12194"/>
				<path id="perso8" class="schemaElement arrow" d="M 40101,11866 L 40593,11538"/>
				<path id="perso9" class="schemaElement arrow" d="M 42300,10400 L 40469,10899 41135,11898 42300,10400 Z"/>
			</svg>
			<div class="information">
				<p id="show_career" class="show">Survolez un élément de mon parcours pour plus d'informations.</p>

				<p id="info_work">Je suis à la recherche d'un emploi en tant que Développeur Back-End ou Front-End, dans le Haut-Rhin et régions limitrophes.
				<br>N'hésitez pas à me contacter !</p>
				<p id="info_perso">A l'issue de ma formation, j'ai dû réaliser un site pour la valider : ce site.
				<br>En parallèle, j'ai réfléchi à certains projets persos.
				<br>Vous trouverez l'ensemble de mes réalisations et projets sur ce site.</p>
				<p id="info_formation">La formation proposée par la 3W Academy (3wa.fr) est une formation intensive de niveau Bac+2. Je l'ai effectué pendant l'Été 2016, à Strasbourg.</p>
				<p id="info_old">J'ai effectué de nombreux emplois n'ayant aucun rapport direct avec la programmation.
				<br>En revanche j'ai pu y acquérir des compétences utiles comme l'Autonomie ou la notion du Besoin Client.</p>
			</div>
		</div>
		<p class="only_small">Visionnez le site sur grand écran pour plus d'informations</p>
		
	</section>
</div>