<div class="form scrollTarget">
	<form method="POST">
		<input type="hidden" name="action" value="newPwd">
		<ul>
			<li>
				<label for='actualPwd'>Mot de Passe actuel</label>
				<input type="password" name="actualPwd" id="actualPwd" placeholder="Votre mot de passe...">
			</li>
			<li>
				<label for='newPwd'>Nouveau Mot de Passe</label>
				<input type="password"	name="newPwd" id="newPwd" placeholder="Votre nouveau mot de passe...">
			</li>
			<li>
				<label for='newPwd2'>Confirmer Nouveau MdP</label>
				<input type="password"	name="newPwd2" id="newPwd2" placeholder="Retapez votre nouveau mot de passe...">
			</li>
			<li>
				<input type=submit value="Modifier le mot de passe">
			</li>
		</ul>						
	</form>
</div>