<div id="<?= $comment->getId(); ?>" class="comment">
	<p class="comment_content"><?= htmlentities($comment->getContent()) ?></p>
	<p class="comment_author"><?= htmlentities($comment->getAuthor()->getLogin()) ?> <br> <span class="comment_date"> le <?= htmlentities($comment->getFormatedDate()); ?></span></p>
	<div class="comment_admin">
		<?php require('controllers/comment_admin.php'); ?>
	</div>
</div>