<div class="layout left">
	<h2>Contact</h2>
	<div class="contact_info">
		<p>Un poste à proposer ? Besoin d'un site ? Une question sur mon travail ? Besoin d'aide pour réaliser un projet ? <br> N'hésitez pas à me contacter !</p>
		<p>Si le formulaire de contact ne fonctionne pas, contactez-moi par mail : <a href="mailto:contact@doudoupike.fr">contact@doudoupike.fr</a>.</p>
		<a class="toggle_large" href="index.php?page=contact&s">Me contacter</a>
	</div>
</div>
<div class="layout right">
	<div class="fade single">
		<div class="contact_form">
			<div class="form scrollTarget">
				<?php require("controllers/contact_display.php") ?>
			</div>
		</div>
	</div>
</div>