<div class="layout left">
	<h2>Contact</h2>
	<div class="contact_info">
		<p>Un poste à proposer ?
		<br>Besoin d'un site ?
		<br>Une question sur mon travail ?
		<br>Besoin d'aide pour réaliser un projet ?</p>
		<p>N'hésitez pas à <a href="index.php?page=contact&s">me contacter</a> !</p>
		<p>Si le formulaire de contact ne fonctionne pas, contactez-moi par mail : <a href="mailto:contact@doudoupike.fr">contact@doudoupike.fr</a>.</p>
	</div>

	<a class="toggle_large scrollArrow" href="index.php?page=contact&s"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>

</div>
<div class="layout right">

	<div class="toggle_large scrollTarget"></div>

	<div class="fade single">
		<div class="contact_form">
			<div class="form scrollTarget">
				<?php require("controllers/contact_display.php") ?>
			</div>
		</div>
	</div>
</div>