<form method="post">
	<input type="hidden" name="action" value="contact">
	<ul>
		<li>
			<label for="pseudo">Pseudo</label>
			<input id="pseudo" type="text" name="pseudo" placeholder="Votre pseudo..." required>
		</li>
		<li>
			<label for="email">Email</label>
			<input id="email" type="email" name="email" placeholder="Votre email..." required>
		</li>
		<li>
			<label for="object">Objet</label>
			<input id="object" type="text" name="object" placeholder="Raison du message..." required>
		</li>
		<li>
			<label for="message">Message</label>
			<textarea id="message" name="message" placeholder="Votre message..." required></textarea>
		</li>
		<li>
			<input type="submit" value="Envoyer">
		</li>
	</ul>	
</form>