<h2>Créer une nouveauté :</h2>
<form method="POST">
	<input type="hidden" name="action" value="create">
	<input type="hidden" name="id_project" value="<?= $_GET['id'] ?>">
	<input type="text" name="title" value="<?= htmlentities($title) ?>" placeholder="titre">
	<textarea name="content" placeholder="contenu"><?= htmlentities($content) ?></textarea>
	<input type="submit" value="Ajouter nouveauté">
</form>