<h2>Ajouter un nouveau projet :</h2>
<form method="POST">
	<input type="hidden" name="action" value="create" >
	<input type="text" name="title" value="<?= htmlentities($title) ?>" placeholder="title">
	<textarea name="content" placeholder="contenu"><?= htmlentities($content) ?></textarea>
	<input type="text" name="image" value="<?= htmlentities($image) ?>" placeholder="image.jpg">
	<input type="url" name="url" value="<?= htmlentities($url) ?>" placeholder="url">
	<input type="text" name="date" value="<?= htmlentities($date) ?>" id="datepicker" placeholder="date">
	<input type="submit" value="Ajouter le projet">
</form>