<form method="POST">
	<input type="hidden" name="action" value="create">
	<input type="hidden" name="id_project" value="<?= $project->getId() ?>">
	<div class="textarea">
		<textarea id="comment_text" name="content" placeholder="Mon commentaire..."><?= htmlentities($content) ?></textarea>
		<div class="count">
			<p id="comment_count">250</p>
		</div>
	</div>	
	<input id="comment_submit" type="submit" value="Commenter">
</form>