<div class="layout left">
	<div class="dashboard">
	<h2>Mon compte</h2>
		<?php require("controllers/access.php"); ?>
		<section class="account">
			<p class="user_info"><span>Pseudo:</span><?= $user->getLogin() ?></p>
			<p class="user_info">
				<span>Email:</span>
				<?= $user->getEmail() ?>
				<span><a href="index.php?page=dashboard&me"><i class="fa fa-pencil" aria-hidden="true"></i></a></span>
				</p>
			<p class="user_info">
				<span>Mot de passe:</span>
				•••••••••••••••
				<span><a href="index.php?page=dashboard&mp"><i class="fa fa-pencil" aria-hidden="true"></i></a></span>
			</p>
			<p class="account_delete"><a href="index.php?page=dashboard&da">Supprimer mon compte</a></p>
		</section>
		<section class="comments_list">
			<h3>Mes commentaires</h3>
			<?php require('controllers/comment.php'); ?>
		</section>
	</div>
</div>
<div class="layout right">
	<div class="fade single">
		<div class="account_modify">
			<?php require('controllers/account.php'); ?>
		</div>
	</div>
</div>