<h2>Editer le projet <?= $project->getId() ?> ?</h2>
<form method="POST">
	<input type="hidden" name="action" value="edit">
	<input type="hidden" name="id" value="<?= $project->getId() ?>">
	<input type="text" name="title" value="<?= htmlentities($project->getTitle()) ?>">
	<textarea name="content"><?= htmlentities($project->getContent()) ?></textarea>
	<input type="text" name="image" value="<?= htmlentities($project->getImage()) ?>">
	<input type="url" name="url" value="<?= htmlentities($project->getUrl()) ?>">
	<input type="text" name="date" placeholder="date" id="datepicker" value="<?= htmlentities($project->getFormatedDate()) ?>">
	<input type="submit" id="send" value="Modifier projet">
</form>
<a href="index.php?admin&page=project_back#<?= $project->getId() ?>">Annuler</a>