<h2>Editer la review <?= $review->getId() ?> ?</h2>
<form method="POST">
	<input type="hidden" name="action" value="edit">
	<input type="hidden" name="id" value="<?= $review->getId() ?>">
	<input type="text" name="title" value="<?= htmlentities($review->getTitle()) ?>">
	<textarea name="content"><?= htmlentities($review->getContent()) ?></textarea>
	<input type="submit" value="Editer">
</form>
<a href="index.php?admin&page=projects#<?= $review->getProject()->getId() ?>">Annuler</a>