<h2>Editer la réalisation <?= $prod->getId() ?> ?</h2>
<form method="POST">
	<input type="hidden" name="action" value="edit">
	<input type="hidden" name="id" value="<?= $prod->getId() ?>">
	<input type="text" name="title" value="<?= htmlentities($prod->getTitle()) ?>">
	<textarea name="description"><?= htmlentities($prod->getDescription()) ?></textarea>
	<input type="text" name="image" value="<?= htmlentities($prod->getImage()) ?>">
	<input type="url" name="url" value="<?= htmlentities($prod->getUrl()) ?>">
	<input type="text" name="client" value="<?= htmlentities($prod->getClient())?>">
	<input type="text" name="date" placeholder="date" id="datepicker" value="<?= htmlentities($prod->getFormatedDate()) ?>">
	<input type="submit" id="send" value="Modifier réalisation">
</form>
<p><a href="index.php?admin&page=prod_back#<?= $prod->getId() ?>">Annuler</a></p>