<main class="container-home">
	<div class="clearfix">
		<div class="cate-home box1">
			<h2><a href="#" class="a-h">Graines de cannabis féminisées</a></h2>
			<p>
				Les graines de cannabis féminisées rendent la culture encore plus facile, puisqu’il n’y a aucun plant mâle a éliminer. Les graines féminisées peuvent pousser dans les mêmes conditions que les graines régulières.
			</p>
			<div class="buttonSeeds">
				<a href="#" class="a-buy">Acheter</a>
			</div>
		</div>
		<div class="cate-home box2">
			<h2><a href="#" class="a-h">Graines de cannabis à autofloraison</a></h2>
			<p>
				Parfaites pour les cultivateurs de cannabis débutants souhaitant obtenir de magnifiques têtes denses ! Achetez des graines à autofloraison ici.
			</p>
			<div class="buttonSeeds">
				<a href="#" class="a-buy">Acheter</a>
			</div>
		</div>
		<div class="cate-home box3">
			<h2><a href="#" class="a-h">Graines de cannabis</a></h2>
			<p>
				Choisissez vos graines de cannabis parmi la sélection du meilleur spécialiste qui soit ! Avis de cultivateurs, paiement sécurisé, et livraison gratuite.
			</p>
			<div class="buttonSeeds">
				<a href="#" class="a-buy">Acheter</a>
			</div>
		</div>
	</div>
	<div class="location clearfix">
		<img src="public/images/poney_home.jpg" class="img-poney">
		<div class="loc">
			<a href="#" class="poney">Location de poneys</a>
			<p>
				Le poney trouve ses origines dans des populations de chevaux sauvages qui se sont développées en marge de l'habitat favori du cheval, dans des zones où la nourriture est rare ou le climat rigoureux, leur petite taille résulterait donc d'une sélection naturelle et d'une adaptation à leur environnement. Ces animaux ont été domestiqués et élevés en captivité à des fins diverses, partout dans l'hémisphère Nord. Les poneys ont été utilisés par le passé pour la conduite et le transport de marchandises, ainsi que pour la monte des enfants, l'équitation de loisir, et plus tard en tant que montures de concours ou de spectacle.
			</p>
		</div>
	</div>
</main>