<div class="layout left">
	<div class="home">
		<div class="title">
			<h1>Kévin Pique <br> alias <strong>DoudouPike</strong></h1>
			<h2>- Développeur Web Full-Stack -</h2>
		</div>
		<div class="description">
			<p class="citation">"Si un site est un iceberg, alors le Back-End est la partie immergée, la partie technique qui le fait rester à la surface. Le Front-End est quant à lui la partie flottant à la surface, la partie visuelle qui est taillée de façon à donner un intérêt à l'ensemble"</p>
			<ul class="social_main">
				<li>
					<a class="button" href="https://www.facebook.com/" target="blank_"><span class="fa fa-facebook"></span></a>
				</li>
				<li>
					<a class="button" href="https://www.twitter.com/" target="blank_"><span class="fa fa-twitter"></span></a>
				</li>
				<li>
					<a class="button" href="https://github.com/DoudouPike" target="blank_"><span class="fa fa-github"></span></a>
				</li>
			</ul>
		</div>
		<aside class="notes">
			<h3>Notes :</h3>
			<div class="notes_container">
				<?php require('controllers/notes.php'); ?>
			</div>
		</aside>
	</div>
</div>
<div class="layout right">
	<div class="home_prods">
		<h2 class="previews_title">Quelques-unes de mes réalisations</h2>
		<div class="previewBox_home">
			<section class="previewsBox">
				<?php require('controllers/prods.php'); ?>
			</section>
		</div>
		<a class="home_redirect" href="index.php?page=portfolio">Voir toutes mes réalisations</a>
	</div>
	<div class="home_projects">
		<h2 class="previews_title">Quelques-uns de mes projets</h2>
		<div class="previewsBox_home">
			<section class="previewsBox">
					<?php require('controllers/projects.php'); ?>
			</section>
		</div>
		<a class="home_redirect" href="index.php?page=mmine">Voir tous mes projets</a>
	</div>
</div>