<div class="layout left">
	<div class="home">
		<div class="home_title">
			<h1>Kévin Pique <br> alias DoudouPike</h1>
			<h2><strong>- Développeur Web Front & Back -</strong></h2>
		</div>
		<div class="home_description">
			<p>Moi c'est Kévin, mais on me connait plus sous le pseudo DoudouPike.
			<br>Ici vous trouverez l'ensemble de mes réalisations et projets Webs.
			<br>N'hésitez pas à donner votre avis sur mon travail. Bonne visite !</p>
			<ul class="social_main">
				<li>
					<a class="button" href="https://www.facebook.com/DoudouPikeWeb/" target="blank_"><span class="fa fa-facebook"></span></a>
				</li>
				<!--
				<li>
					<a class="button" href="https://twitter.com" target="blank_"><span class="fa fa-twitter"></span></a>
				</li> -->
				<li>
					<a class="button" href="https://www.linkedin.com/in/kévin-pique-2040bb136" target="blank_"><span class="fa fa-linkedin"></span></a>
				</li>
				<li>
					<a class="button" href="https://github.com/DoudouPike" target="blank_"><span class="fa fa-github"></span></a>
				</li>
			</ul>
			<p>© 2016-2017 - <a href="http://doudoupike.fr">DoudouPike</a></p>
		</div>
		<aside class="notes">
			<h3>Notes :</h3>
			<div class="notes_container">
				<?php require('controllers/note.php'); ?>
			</div>
		</aside>
	</div>
</div>
<div class="layout right">
	<section class="home_prods">
		<h2>Quelques-unes de mes réalisations</h2>
		<div class="previewsBox_home">
			<?php require('controllers/prod_preview.php'); ?>
		</div>
		<a class="home_redirect" href="index.php?page=portfolio">Voir toutes mes réalisations</a>
	</section>
	<section class="home_projects">
		<h2>Quelques-uns de mes projets</h2>
		<div class="previewsBox_home">
				<?php require('controllers/project_preview.php'); ?>
		</div>
		<a class="home_redirect" href="index.php?page=mine">Voir tous mes projets</a>
	</section>
</div>