<div class="myAccount">
	<form method="post">
		<h2 class="registerTitle">MON COMPTE :</h2>
		<label>Pseudo</label>
		<input type="text" placeholder="Choisissez un pseudo" name="login" />
		<label>Choisissez un mot de passe</label>
		<input type="password" placeholder="Entrez votre mot de passe" name="pwd" />
		<input type="hidden" name="action" value="login">
		<button class="loginButton" type="submit" value="login">Entrer</button>
	</form>
</div>