<ul class="menu_admin">
	<li class="logo"><a href="index.php?admin&page=home" title="Accueil BackOffice"><img src="public/images/logo.png" alt="Logo DoudouPike"></a></li>
	<li class="submenu">
		<p>Notes</p>
		<ul>
			<li><a href="index.php?admin&page=notes">Toutes les notes</a></li>
			<li><a href="index.php?admin&page=create_note">Ajouter une note</a></li>
		</ul>
	</li>
	<li class="submenu">
		<p>Réalisations</p>
		<ul>
			<li><a href="index.php?admin&page=">Toutes les réalisations</a></li>
			<li><a href="index.php?admin&page=">Ajouter une réalisation</a></li>
		</ul>
	</li>
	<li class="submenu">
		<p>Projets</p>
		<ul>
			<li><a href="index.php?admin&page=">Tous les projets</a></li>
			<li><a href="index.php?admin&page=">Ajouter un projets</a></li>
		</ul>
	</li>
	<li><a href="index.php?admin&page=">Utilisateurs</a></li>
</ul>