<div class="menuBack">
	<ul>
		<li class="logo"><a href="index.php?admin&page=home_back" title="Accueil BackOffice"><img src="public/images/logo.png" alt="Logo DoudouPike"></a></li>
		<li class="submenu">
			<p><span class="fa fa-file-o"></span></p>
			<ul>
				<li><a href="index.php?admin&page=notes_back">Toutes les notes</a></li>
				<li><a href="index.php?admin&page=create_note">Ajouter une note</a></li>
			</ul>
		</li>
		<li class="submenu">
			<p><span class="fa fa-book"></span></p>
			<ul>
				<li><a href="index.php?admin&page=prods">Toutes les réalisations</a></li>
				<li><a href="index.php?admin&page=create_prod">Ajouter une réalisation</a></li>
			</ul>
		</li>
		<li class="submenu">
			<p><span class="fa fa-lightbulb-o"></span></p>
			<ul>
				<li><a href="index.php?admin&page=projects">Tous les projets</a></li>
				<li><a href="index.php?admin&page=create_project">Ajouter un projet</a></li>
			</ul>
		</li>
		<li><a href="index.php?admin&page=users"><span class="fa fa-user"></span></a></li>
	</ul>
</div>