<ul class="menu_admin">
	<li class="logo"><a href="index.php?admin&page=home" title="Accueil BackOffice"><img src="public/images/logo.png" alt="Logo DoudouPike"></a></li>
	<li class="submenu">
		<p>Notes</p>
		<ul>
			<li><a href="#">Toutes les notes</a></li>
			<li><a href="#">Ajouter une note</a></li>
		</ul>
	</li>
	<li class="submenu">
		<p>Réalisations</p>
		<ul>
			<li><a href="#">Toutes les réalisations</a></li>
			<li><a href="#">Ajouter une réalisation</a></li>
		</ul>
	</li>
	<li class="submenu">
		<p>Projets</p>
		<ul>
			<li><a href="#">Tous les projets</a></li>
			<li><a href="#">Ajouter un projets</a></li>
		</ul>
	</li>
	<li><a href="#">Utilisateurs</a></li>
</ul>