<nav class="menu">
	<ul>
		<li>
			<a href="">
				<img class="reduceMenu" src="public/images/logo.png" alt="logo">
				<span class="fullMenu">DoudouPike</span>
			</a>
		</li>
		<li>
			<ul>
				<li>
					<a href="">
						<span class="reduceMenu fa fa-book"></span>
						<span class="fullMenu">Portfolio</span>
					</a>
				</li>
				<li>
					<a href="">
						<span class="reduceMenu fa fa-lightbulb-o"></span>
						<span class="fullMenu">Projets</span>
					</a>
				</li>
				<li>
					<a href="">
						<span class="reduceMenu fa fa-phone"></span>
						<span class="fullMenu">A propos</span>
					</a>
				</li>
			</ul>
		</li>
	</ul>
</nav>