<div class="menuPublic">
	<ul class="links">
		<li id="link_home" class="menu_page">
			<a href="index.php?page=home"><img class="logo" src="public/images/menu/logo.gif" alt=""></a>
		</li>
		<li id="link_about" class="menu_page">
			<a href="index.php?page=about"><img src="public/images/menu/about.gif" alt=""></a>
		</li>
		<li id="link_prod" class="menu_page">
			<a href="index.php?page=portfolio"><img src="public/images/menu/prod.gif" alt=""></a>
		</li>
		<li id="link_project" class="menu_page">
			<a href="index.php?page=mine"><img src="public/images/menu/project.gif" alt=""></a>
		</li>
		<li id="link_contact" class="menu_page">
			<a href="index.php?page=contact" title="Me contacter"><img src="public/images/menu/contact.gif" alt=""></a>
		</li>
	</ul>
	<ul class="social_menu">
		<!-- <li>
			<a class="button" href="https://www.facebook.com/" target="blank_"><span class="fa fa-facebook"></span></a>
		</li>
		<li>
			<a class="button" href="https://www.twitter.com/" target="blank_"><span class="fa fa-twitter"></span></a>
		</li> -->
		<li>
			<a class="button" href="https://github.com/DoudouPike" target="blank_"><span class="fa fa-github"></span></a>
		</li>
	</ul>
</div>