<div class="preview">
	<div class="previewImage" style="background-image: url('public/images/prods/<?= htmlentities($prod->getImage()) ?>')">
		<a href="index.php?page=portfolio&id=<?= $prod->getId() ?>">
			<div class="previewFilm">
				<div class="previewContent">
					<h5><?= htmlentities($prod->getTitle()) ?></h5>
					<p><?= htmlentities($prod->getDescription()) ?></p>
				</div>
			</div>
		</a>
	</div>
</div>