<div class="fade single scrollTarget">
	<article class="prod">
		<h3 class="single_title"><?= htmlentities($prod->getTitle()) ?></h3>
		<figure class="single_image prod_image">
			<a href="<?= htmlentities($prod->getUrl()) ?>" >
				<img src="public/images/prods/<?= htmlentities($prod->getImage()) ?>" alt='illustration du projet'>
			</a>
		</figure>
		<div class="prod_content">
			<div class="prod_description">
				<div>
					<p><?= htmlentities($prod->getDescription()) ?></p>
				</div>
			</div>
			<div class="prod_informations">
				<div>
					<p>Réalisé le : <?= htmlentities($prod->getFormatedDate()) ?></p>
					<p>Pour : <?= htmlentities($prod->getClient()) ?></p>
					<p><a href="<?= htmlentities($prod->getUrl()) ?>" ><i class="fa fa-external-link" aria-hidden="true"></i> <?= htmlentities($prod->getUrl()) ?></a></p>
				</div>
			</div>
		</div>
	</article>
</div>