<article class="prod">
	<h3 class="single_title"><?= htmlentities($prod->getTitle()) ?></h3>
	<figure class="single_image prod_image">
		<img src="public/images/prods/<?= htmlentities($prod->getImage()) ?>" alt='illustration du projet'>
	</figure>
	<div class="prod_content">
		<div class="prod_description">
			<div>
				<p><?= htmlentities($prod->getDescription()) ?></p>
			</div>
		</div>
		<div class="prod_informations">
			<div>
				<p>Réalisé le : <?= htmlentities($prod->getFormatedDate()) ?></p>
				<p>Pour : <?= htmlentities($prod->getClient()) ?></p>
				<p><a href="<?= htmlentities($prod->getUrl()) ?>"><?= htmlentities($prod->getUrl()) ?></a></p>
			</div>
		</div>
	</div>
</article>