<div class="fade single scrollTarget">
	<article class="project">
		<h3 class="single_title"><?= htmlentities($project->getTitle()) ?><span class="project_lastDate">Dernière modif: <?=htmlentities($project->getLastDate()) ?></span></h3>
		<div class="project_presentation">
			<figure class="single_image project_image">
				<img src="public/images/projects/<?= htmlentities($project->getImage()) ?>" alt='illustration du projet'>
			</figure>
			<div class="project_content">
				<div class="project_description">
					<p><?= htmlentities($project->getContent()) ?></p>
				</div>
				<div class="project_information">
					<p>Débuté le: <?= htmlentities($project->getFormatedDate()) ?></p>
					<p><a href="<?= htmlentities($project->getUrl()) ?>" target="_blank"><i class="fa fa-external-link" aria-hidden="true"></i> <?= htmlentities($project->getUrl()) ?></a></p>
				</div>
			</div>
		</div>
		<div class="project_news">
			<div class="reviews">
				<h4>Actualités</h4>
				<div class="reviews_list">
					<?php require('controllers/review.php') ?>
				</div>
			</div>
			<p class="only_small">Visionnez le site sur grand écran pour plus d'informations</p>
			<div class="comments">
				<h4>Commentaires</h4>
				<div class="comment_create">
					<?php require('controllers/create_comment.php'); ?>
				</div>
				<div class="comments_list">
					<?php require('controllers/comment.php'); ?>
				</div>
			</div>
		</div>
	</article>
</div>