<div id="<?= $tabs[$i]->getId() ?>" style="background-image:<?= htmlentities($tabs[$i]->getImage()) ?>">
	<p><?= htmlentities($tabs[$i]->getTitle()) ?></p>
	<p><?= htmlentities($tabs[$i]->getAbstract()) ?></p>
	
	<div>
		<a href="index.php?admin&page=reviews&id=<?= $tabs[$i]->getId() ?>">Voir les reviews de ce projet</a>
		<a href="index.php?admin&page=comments&id=<?= $tabs[$i]->getId() ?>">Voir les commentaires de ce projet</a>
	</div>
	
	<div><?php require('controllers/buttons_admin.php'); ?></div>
</div>