<div class="preview">
	<div class="previewImage" style="background-image: url('public/images/prods/<?= htmlentities($project->getImage()) ?>')">
		<a href="index.php?page=mine&id=<?= $project->getId() ?>">
			<div class="previewFilm">
				<div class="previewContent">
					<h5><?= htmlentities($project->getTitle()) ?></h5>
					<p><?= htmlentities($project->getAbstract()) ?></p>
				</div>
			</div>
		</a>
	</div>
</div>