<div id="<?= $project->getId() ?>" style="background: url('public/images/projects/<?= htmlentities($project->getImage()) ?>') center center no-repeat">
	<p><?= htmlentities($project->getTitle()) ?></p>
	<p>ajouté le: <?= htmlentities($project->getFormatedDate()) ?></p>
	<p>dernière modification: <?= htmlentities($project->getLastDate()) ?></p>
	<div><?php require('controllers/project_admin.php'); ?></div>
	
	<div>
		<div>
			<h4>Les nouveautés :</h4>
			<a class="fa fa-plus" href="index.php?admin&page=create_review&id=<?= $project->getId() ?>" title="Ajouter une nouveauté"></a>
			<?php require('controllers/review_back.php'); ?>
		</div>
		<div>
			<h4>Les commentaires :</h4>
			<a class="fa fa-plus" href="index.php?admin&page=create_comment&id=<?= $project->getId() ?>" title="Ajouter un commentaire"></a>
			<?php require('controllers/comment_back.php'); ?>
		</div>
	</div>
</div>