<form method="post">
	<input type="hidden" name="action" value="register">
	<input type="text" name="login" value="<?= htmlentities($login) ?>" placeholder="Pseudo" >
	<input type="email" name="email" value="<?= htmlentities($email) ?>" placeholder="Email" >
	<input type="password" name="pwd" placeholder="Mot de passe" >
	<input type="password" name="pwd2" placeholder="Confirmation mot de passe" >
	<input type="submit" value="S'enregistrer" >
		
	<!-- <div class="clearfix checkbox">
		<div class="majority">
			<label for="majority">j'ai 18 ans ou plus, et j'accepte les <a class="userAgreement" href="http://www.apple.com/legal/internet-services/itunes/fr/terms.html" target="_blank">conditions d'utilisation.</a></label>
		</div>
		<div class="majority">
			<input type="checkbox" name="majority" value="majority" id="majority"/>
		</div>
	</div> -->
</form>
