<form class="scrollTarget" method="post">
	<input type="hidden" name="action" value="register">
	<ul>
		<li>
			<label for="pseudo">Pseudo</label>
			<input id="pseudo" type="text" name="login" value="<?= htmlentities($login) ?>" placeholder="Votre pseudo... [4 à 31 caractères]" >
		</li>
		<li>
			<label for="email">Email</label>
			<input id="email" type="email" name="email" value="<?= htmlentities($email) ?>" placeholder="Votre Email..." >
		</li>
		<li>
			<label for="pwd1">Mot de Passe</label>
			<input id="pwd1" type="password" name="pwd" placeholder="Votre mot de passe... [6 caractères min]" >
		</li>
		<li>
			<label for="pwd2">Confirmation MdP</label>
			<input id="pwd2" type="password" name="pwd2" placeholder="Retapez votre mot de passe..." >
		</li>
		<li>
			<input type="submit" value="S'enregistrer" >
		</li>
	</ul>
</form>