<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>TITRE</title>
	<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
	<link rel="stylesheet" type="text/css" href="public/styles/style.min.css">
	<link rel="stylesheet" type="text/css" href="public/font-awesome/css/font-awesome.min.css">
	<!--<script type="text/javascript" src="../public/scripts/less.min.js"></script>-->
	<!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
</head>
<body>
	<div class="container">
		<?php require("apps/header.php"); ?>
		<?php require("apps/menu.php"); ?>
	</div>
</body>
</html>