<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Portfolio</title>
		<link href="public/styles/font-awesome.min.css" rel="stylesheet">
		<!-- <link rel="icon" type="image/x-icon" href="public/images/favicon.ico" /> -->
		<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.min.css">
	</head>
	<body>
		<div class="container">
			<?php require("controllers/display.php") ?>
		</div>
	</body>
</html>