<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>TITRE</title>
	<link rel="stylesheet" type="text/css" href="../public/styles/reset.css">
	<link rel="stylesheet/less" type="text/css" href="../public/styles/style.less">
	<script type="text/javascript" src="../public/scripts/less.min.js"></script>
</head>
<body>
	<header class="header">
		<svg></svg>
		<nav class="social">
			<ul>
				<li><span class="fa fa-"></span></li>
				<li><span class="fa fa-"></span></li>
				<li><span class="fa fa-"></span></li>
			</ul>
		</nav>
	</header>
</body>
</html>